title: Peter Griffen Hell Wiki
description: A wiki for the greatest game, Peter Griffen Hell!
theme: just-the-docs

url: https://thearchie3.github.io/Peter-Griffen-Hell-Wiki/

aux_links:
  Template Repository: https://thearchie3.github.io/Peter-Griffen-Hell-Wiki/
